/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package holistic.dps;

import org.junit.jupiter.api.Test;

class DPSDriverTest {
    @Test void testMain() {
    	// TODO: Do some test!
    }
}
