version: "3"

services:
  therapist_processor:
    build: .
    volumes:
      - .:/data-processing-service
    tty: true
    container_name: therapist_processor
    env_file:
      - .env
    networks:
      - holistic-net
    command:
      - ./run_therapist_processor.sh

  interaction_processor:
    build: .
    volumes:
      - .:/data-processing-service
    tty: true
    container_name: interaction_processor
    env_file:
      - .env
    networks:
      - holistic-net
    command:
      - ./run_interaction_processor.sh

  sync_back:
    build: .
    volumes:
      - .:/data-processing-service
    tty: true
    container_name: sync_back
    env_file:
      - .env
    networks:
      - holistic-net
    command:
      - ./run_sync_back.sh

networks:
  # Use the network bridge so that our containers can talk to each other.
  # @see https://levelup.gitconnected.com/how-to-access-a-docker-container-from-another-container-656398c93576
  holistic-net:
    name: holistic-net
    external: true
