version: "3"

services:
  dps:
    build: .
    volumes:
      - .:/data-processing-service
    tty: true
    container_name: dps
    env_file:
      - .env
    networks:
      - holistic-net
    command:
      - ./run_therapist_processor.sh

networks:
  # Use the network bridge so that our containers can talk to each other.
  # @see https://levelup.gitconnected.com/how-to-access-a-docker-container-from-another-container-656398c93576
  holistic-net:
    name: holistic-net
    external: true
