/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data.aggregator.app;

import org.junit.jupiter.api.Test;

class TherapistAggregatorDriverTest {
    @Test void testMain() {
    	// TODO: Do some test!
    }
}
